import js from '@eslint/js'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'test-results/**',
      'playwright-report/**',
      // Generated by Payload; not ours to lint.
      'src/payload-types.ts',
      'src/app/(payload)/admin/importMap.js',
      'src/migrations/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      // Unused code is the signal we care about; allow _-prefixed escapes.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
  {
    // Config files and tests run in Node and may reach for its globals.
    files: ['*.config.{ts,mjs}', 'tests/**/*.ts', 'src/**/*.test.ts'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly' },
    },
  },
)
